// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

namespace NetPdf.Text.Fonts.Woff;

/// <summary>
/// Constants for WOFF 2.0 file-format parsing. Spec basis: W3C "WOFF File Format 2.0"
/// Recommendation, 1 March 2018 (<c>https://www.w3.org/TR/WOFF2/</c>) §3 + §4. No code
/// transliterated from any third-party implementation.
/// </summary>
internal static class WoffTwoConstants
{
    /// <summary>WOFF 2.0 signature: 'wOF2' (0x774F4632).</summary>
    public const uint Signature = 0x774F4632u;

    /// <summary>SFNT TrueType flavor (version 1.0): 0x00010000.</summary>
    public const uint FlavorTrueType = 0x00010000u;

    /// <summary>SFNT OTF/CFF flavor: 'OTTO' (0x4F54544F).</summary>
    public const uint FlavorCff = 0x4F54544Fu;

    /// <summary>SFNT TrueType collection flavor: 'ttcf' (0x74746366). Phase 1 does not parse collections.</summary>
    public const uint FlavorTtc = 0x74746366u;

    /// <summary>Header size in bytes (§3 Table 1).</summary>
    public const int HeaderSize = 48;

    /// <summary>Sentinel "custom tag follows" value in the low 6 bits of a directory entry's flags byte (§4.1).</summary>
    public const byte CustomTagSentinel = 63;

    /// <summary>
    /// Lookup table for the 63 known WOFF 2.0 table tags, indexed by the low 6 bits of the
    /// flags byte. Index 63 is reserved as the "custom tag follows" sentinel and is never
    /// referenced via this table — see <see cref="CustomTagSentinel"/>. Each tag is the
    /// big-endian 4-byte ASCII value of the OpenType table tag.
    /// </summary>
    /// <remarks>
    /// Order matches W3C WOFF 2.0 §4.1 Table 4 verbatim. Generated by hand from the spec
    /// (data, not implementation code) — clean-room.
    /// </remarks>
    public static readonly uint[] KnownTags =
    [
        Tag('c', 'm', 'a', 'p'),  // 0
        Tag('h', 'e', 'a', 'd'),  // 1
        Tag('h', 'h', 'e', 'a'),  // 2
        Tag('h', 'm', 't', 'x'),  // 3
        Tag('m', 'a', 'x', 'p'),  // 4
        Tag('n', 'a', 'm', 'e'),  // 5
        Tag('O', 'S', '/', '2'),  // 6
        Tag('p', 'o', 's', 't'),  // 7
        Tag('c', 'v', 't', ' '),  // 8
        Tag('f', 'p', 'g', 'm'),  // 9
        Tag('g', 'l', 'y', 'f'),  // 10
        Tag('l', 'o', 'c', 'a'),  // 11
        Tag('p', 'r', 'e', 'p'),  // 12
        Tag('C', 'F', 'F', ' '),  // 13
        Tag('V', 'O', 'R', 'G'),  // 14
        Tag('E', 'B', 'D', 'T'),  // 15
        Tag('E', 'B', 'L', 'C'),  // 16
        Tag('g', 'a', 's', 'p'),  // 17
        Tag('h', 'd', 'm', 'x'),  // 18
        Tag('k', 'e', 'r', 'n'),  // 19
        Tag('L', 'T', 'S', 'H'),  // 20
        Tag('P', 'C', 'L', 'T'),  // 21
        Tag('V', 'D', 'M', 'X'),  // 22
        Tag('v', 'h', 'e', 'a'),  // 23
        Tag('v', 'm', 't', 'x'),  // 24
        Tag('B', 'A', 'S', 'E'),  // 25
        Tag('G', 'D', 'E', 'F'),  // 26
        Tag('G', 'P', 'O', 'S'),  // 27
        Tag('G', 'S', 'U', 'B'),  // 28
        Tag('E', 'B', 'S', 'C'),  // 29
        Tag('J', 'S', 'T', 'F'),  // 30
        Tag('M', 'A', 'T', 'H'),  // 31
        Tag('C', 'B', 'D', 'T'),  // 32
        Tag('C', 'B', 'L', 'C'),  // 33
        Tag('C', 'O', 'L', 'R'),  // 34
        Tag('C', 'P', 'A', 'L'),  // 35
        Tag('S', 'V', 'G', ' '),  // 36
        Tag('s', 'b', 'i', 'x'),  // 37
        Tag('a', 'c', 'n', 't'),  // 38
        Tag('a', 'v', 'a', 'r'),  // 39
        Tag('b', 'd', 'a', 't'),  // 40
        Tag('b', 'l', 'o', 'c'),  // 41
        Tag('b', 's', 'l', 'n'),  // 42
        Tag('c', 'v', 'a', 'r'),  // 43
        Tag('f', 'd', 's', 'c'),  // 44
        Tag('f', 'e', 'a', 't'),  // 45
        Tag('f', 'm', 't', 'x'),  // 46
        Tag('f', 'v', 'a', 'r'),  // 47
        Tag('g', 'v', 'a', 'r'),  // 48
        Tag('h', 's', 't', 'y'),  // 49
        Tag('j', 'u', 's', 't'),  // 50
        Tag('l', 'c', 'a', 'r'),  // 51
        Tag('m', 'o', 'r', 't'),  // 52
        Tag('m', 'o', 'r', 'x'),  // 53
        Tag('o', 'p', 'b', 'd'),  // 54
        Tag('p', 'r', 'o', 'p'),  // 55
        Tag('t', 'r', 'a', 'k'),  // 56
        Tag('Z', 'a', 'p', 'f'),  // 57
        Tag('S', 'i', 'l', 'f'),  // 58
        Tag('G', 'l', 'a', 't'),  // 59
        Tag('G', 'l', 'o', 'c'),  // 60
        Tag('F', 'e', 'a', 't'),  // 61
        Tag('S', 'i', 'l', 'l'),  // 62
    ];

    private static uint Tag(char a, char b, char c, char d) =>
        ((uint)a << 24) | ((uint)b << 16) | ((uint)c << 8) | d;
}
