// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

using NetPdf;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => Results.Text(
    $"NetPdf {HtmlPdf.Version} — try GET /report?title=Q1",
    "text/plain"));

app.MapGet("/report", (string? title) =>
{
    var html = $$"""
        <!DOCTYPE html>
        <html><head><meta charset="utf-8">
            <title>{{title ?? "Untitled"}}</title>
            <style>
                @page { size: Letter; margin: 1in; }
                body { font-family: "Inter", sans-serif; line-height: 1.5; color: #111; }
                h1 { font-size: 32pt; }
            </style>
        </head><body>
            <h1>{{title ?? "Untitled"}} report</h1>
            <p>Generated by NetPdf.</p>
        </body></html>
        """;

    try
    {
        var pdf = HtmlPdf.Convert(html, new HtmlPdfOptions
        {
            Title = title ?? "Untitled",
            Features = FeatureFlags.DeterministicTimestamps,
        });
        return Results.File(pdf, "application/pdf", $"{title ?? "report"}.pdf");
    }
    catch (NotImplementedException ex)
    {
        return Results.Problem(
            title: "NetPdf phase 0",
            detail: ex.Message,
            statusCode: 501);
    }
});

app.Run();
