// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

using System.Security.Cryptography;
using Microsoft.Net.Http.Headers;
using NetPdf;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => Results.Text(
    $"NetPdf {HtmlPdf.Version} — HTML → PDF report service. " +
    "GET /report?title=Q1%20Review returns a PDF with a content-hash ETag for client caching.",
    "text/plain"));

app.MapGet("/report", (string? title, HttpContext ctx) =>
{
    var reportTitle = string.IsNullOrWhiteSpace(title) ? "Untitled" : title.Trim();

    var html = $$"""
        <!DOCTYPE html>
        <html lang="en"><head><meta charset="utf-8">
            <title>{{reportTitle}}</title>
            <style>
                @page { size: Letter; margin: 1in; }
                body { font-family: "Inter", sans-serif; line-height: 1.5; color: #111; }
                h1 { font-size: 32pt; margin: 0 0 .5rem; }
                .muted { color: #888; }
            </style>
        </head><body>
            <h1>{{reportTitle}}</h1>
            <p class="muted">Generated by NetPdf.</p>
        </body></html>
        """;

    byte[] pdf;
    try
    {
        pdf = HtmlPdf.Convert(html, new HtmlPdfOptions
        {
            Title = reportTitle,
            // Deterministic output is what makes the content-hash ETag below stable across requests.
            Features = FeatureFlags.DeterministicTimestamps,
        });
    }
    catch (HtmlPdfException ex)
    {
        // Never corrupt output silently: surface the render failure with its stable diagnostic code.
        return Results.Problem(
            title: $"NetPdf could not render the report [{ex.Code}]",
            detail: ex.Message,
            statusCode: StatusCodes.Status422UnprocessableEntity);
    }

    // The PDF is deterministic, so its content hash is a strong ETag. Results.File wires up proper HTTP
    // caching from it: a conditional GET carrying a matching If-None-Match gets a 304 (no re-send), and
    // Range requests are honored. Cache-Control lets shared caches keep it too.
    var etag = new EntityTagHeaderValue($"\"{Convert.ToHexString(SHA256.HashData(pdf)).ToLowerInvariant()}\"");
    ctx.Response.Headers.CacheControl = "public, max-age=3600";

    var fileName = string.Concat(reportTitle.Split(Path.GetInvalidFileNameChars())) + ".pdf";
    return Results.File(
        pdf,
        contentType: "application/pdf",
        fileDownloadName: fileName,
        enableRangeProcessing: true,
        entityTag: etag);
});

app.Run();
