// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

namespace NetPdf.Layout.Boxes;

/// <summary>
/// Classification of a <see cref="Box"/>'s layout role per CSS Display L3 §2 (the
/// outer / inner display dichotomy) plus the module-specific box types from
/// CSS Inline L3, Lists L3, Tables L3, Flexbox 1, and Grid 2. The enum is the
/// dispatch key for Phase 3 layout — block boxes lay out their children
/// vertically per the BFC / IFC rules, inline boxes participate in line
/// construction, table boxes follow the §4 table model, etc.
/// </summary>
/// <remarks>
/// <para>
/// <b>Granularity choice.</b> A single concrete <see cref="Box"/> with a
/// <see cref="BoxKind"/> discriminator (rather than a class hierarchy) keeps
/// allocation simple, matches the codebase's pattern for typed-value
/// dispatch (see <see cref="NetPdf.Css.Properties.PropertyType"/>), and avoids
/// the "deep inheritance graph that nobody can navigate" problem that bigger
/// engines suffer from.
/// </para>
/// <para>
/// <b>Why no separate "ListItem" outer-display + "ListItem" inner-display.</b>
/// Per Display L3 §2.4, <c>list-item</c> is a marker layout-mode hint on a
/// block container — the principal box is still a block. We model it as a
/// single <see cref="ListItem"/> kind because the marker box (a separate
/// <see cref="Marker"/> kind) is the only structural difference, and
/// representing the marker as its own box with the right
/// <see cref="BoxPseudo.Marker"/> pseudo discriminator lets layout treat
/// <c>::marker</c> placement uniformly without a discriminator on the parent.
/// </para>
/// <para>
/// <b>Anonymous boxes</b> per Display L3 §3 + Tables L3 §3 (table fixup):
/// distinct values for <see cref="AnonymousBlock"/> + <see cref="AnonymousInline"/>
/// because Phase 3 layout needs to distinguish "synthesized for block-in-inline
/// containment" from "synthesized for inline-in-block containment". <see cref="LineBox"/>
/// is its own value — it's the per-line container produced during inline layout,
/// not an anonymous synthetic from box generation.
/// </para>
/// <para>
/// <b>Out of scope (Phase 3+):</b> ruby boxes, math boxes, multicol boxes,
/// SVG boxes, and the various fragmentation-specific boxes (column box,
/// page box, region box). Those land alongside the layout passes that
/// produce them.
/// </para>
/// </remarks>
internal enum BoxKind : byte
{
    /// <summary>The single root of the box tree corresponding to the page /
    /// initial containing block. Generated by <c>BoxBuilder</c> as the parent
    /// of the root element's principal box.</summary>
    Root = 0,

    // ============================================================
    // Block-level (CSS Display L3 §2.4)
    // ============================================================

    /// <summary>A block-level box that establishes a block formatting context
    /// for its in-flow children — the default for <c>div</c>, <c>p</c>,
    /// <c>section</c>, etc. Per CSS Display L3 §2.4 + §3, this is the
    /// principal box for elements with <c>display: block</c> (and the inner
    /// display fallback for many other types). Lays out children vertically.</summary>
    BlockContainer,

    // ============================================================
    // Inline-level (CSS Display L3 §2.4 + Inline L3)
    // ============================================================

    /// <summary>An inline-level non-replaced box — <c>span</c>, <c>em</c>,
    /// <c>a</c>. Participates in the parent's inline formatting context by
    /// contributing inline runs to line boxes. Per Inline L3 §2.</summary>
    InlineBox,

    /// <summary>An inline-level replaced box or block-level box flowing inline
    /// (<c>display: inline-block</c>, <c>display: inline-table</c>,
    /// <c>display: inline-flex</c>, <c>display: inline-grid</c>). Treated as a
    /// single atomic unit by line layout — the inner formatting context lays
    /// out independently of the surrounding inline context per Inline L3 §1.</summary>
    AtomicInline,

    /// <summary>A line box — the per-line container of inline-level boxes
    /// produced by inline-formatting-context layout per Inline L3 §3. One per
    /// rendered line; distinct from <see cref="AnonymousInline"/> which is a
    /// box-generation artifact.</summary>
    LineBox,

    /// <summary>A contiguous run of text characters within an inline parent.
    /// The smallest text unit Phase 3 segments, shapes, and breaks. Carries
    /// its text in <see cref="Box.Text"/>.</summary>
    TextRun,

    // ============================================================
    // Lists (CSS Lists L3)
    // ============================================================

    /// <summary>An <c>li</c> element or anything with <c>display: list-item</c>
    /// per Lists L3 §3. Behaves as a <see cref="BlockContainer"/> for layout
    /// but is associated with a separate <see cref="Marker"/> child box.</summary>
    ListItem,

    /// <summary>The marker box for a <c>list-item</c> per Lists L3 §3.1, or
    /// the <c>::marker</c> pseudo-element box per CSS Pseudo L4 §3.4. Always
    /// has <see cref="BoxPseudo.Marker"/> when generated from a pseudo-element
    /// rule.</summary>
    Marker,

    // ============================================================
    // Tables (CSS Tables L3 §2)
    // ============================================================

    /// <summary>The principal table-wrapper box for an element with
    /// <c>display: table</c> or the implicit table generated by table fixup
    /// per Tables L3 §3.</summary>
    Table,

    /// <summary>A row group: <c>tbody</c> or anything with
    /// <c>display: table-row-group</c>.</summary>
    TableRowGroup,

    /// <summary><c>thead</c> or <c>display: table-header-group</c>.</summary>
    TableHeaderGroup,

    /// <summary><c>tfoot</c> or <c>display: table-footer-group</c>.</summary>
    TableFooterGroup,

    /// <summary><c>tr</c> or <c>display: table-row</c>.</summary>
    TableRow,

    /// <summary><c>td</c> / <c>th</c> or <c>display: table-cell</c>.</summary>
    TableCell,

    /// <summary><c>colgroup</c> or <c>display: table-column-group</c>.</summary>
    TableColumnGroup,

    /// <summary><c>col</c> or <c>display: table-column</c>.</summary>
    TableColumn,

    /// <summary><c>caption</c> or <c>display: table-caption</c>.</summary>
    TableCaption,

    // ============================================================
    // Flexbox (CSS Flexbox 1 §3)
    // ============================================================

    /// <summary>A flex container — <c>display: flex</c> or <c>display: inline-flex</c>.
    /// Lays out its <see cref="FlexItem"/> children per the flex algorithm in §9.</summary>
    FlexContainer,

    /// <summary>A flex item — every in-flow child of a <see cref="FlexContainer"/>.
    /// Anonymous text runs in a flex container are wrapped in synthetic flex
    /// items per §4.</summary>
    FlexItem,

    // ============================================================
    // Grid (CSS Grid 2 §3)
    // ============================================================

    /// <summary>A grid container — <c>display: grid</c> or <c>display: inline-grid</c>.
    /// Establishes a grid formatting context for its <see cref="GridItem"/>
    /// children per the grid placement + sizing algorithms in §6 + §11.</summary>
    GridContainer,

    /// <summary>A grid item — every in-flow child of a <see cref="GridContainer"/>.
    /// Same anonymous-wrapping rules as flex items.</summary>
    GridItem,

    // ============================================================
    // Replaced content (CSS Display L3 §2.4 + Replaced L4)
    // ============================================================

    /// <summary>A replaced element box — <c>img</c>, <c>video</c>, <c>canvas</c>,
    /// <c>iframe</c>, <c>object</c>, <c>embed</c>. The intrinsic content
    /// (image bytes, video frame, etc.) is opaque to the layout engine —
    /// only the intrinsic dimensions matter for sizing per Sizing 3 §5.</summary>
    ReplacedElement,

    // ============================================================
    // Anonymous boxes (CSS Display L3 §3 + Tables L3 §3 fixup)
    // ============================================================

    /// <summary>An anonymous block-level box synthesized to maintain the
    /// invariant that block + inline siblings cannot mix in the same
    /// formatting context per Display L3 §3.1, OR to satisfy table fixup per
    /// Tables L3 §3 (e.g., a stray block inside a table row gets wrapped).
    /// Has no <see cref="Box.SourceElement"/>; inherits style from its parent.</summary>
    AnonymousBlock,

    /// <summary>An anonymous inline-level box wrapping anonymous text content
    /// per Display L3 §3.2 (e.g., a text node directly inside a flex
    /// container becomes a wrapped flex-item-anon-inline). Distinct from
    /// <see cref="LineBox"/>: this is a box-generation construct,
    /// <see cref="LineBox"/> is a line-layout product.</summary>
    AnonymousInline,
}
