// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

namespace NetPdf.Layout.Boxes;

/// <summary>
/// Classification of a <see cref="Box"/>'s layout role per CSS Display L3 §2 (the
/// outer × inner display dichotomy) plus the module-specific box types from
/// CSS Inline L3, Lists L3, Tables L3, Flexbox 1, and Grid 2. The enum is the
/// dispatch key for Phase 3 layout — block boxes lay out their children
/// vertically per the BFC / IFC rules, inline-level boxes participate in line
/// construction, table boxes follow the §4 table model, etc.
/// </summary>
/// <remarks>
/// <para>
/// <b>Outer × inner display.</b> CSS Display L3 §2 splits a box's display into an
/// outer type (<c>block</c> / <c>inline</c>) and an inner formatting context
/// (<c>flow</c> / <c>flow-root</c> / <c>flex</c> / <c>grid</c> / <c>table</c> /
/// <c>ruby</c>). We encode the cross product as explicit kinds — e.g.,
/// <see cref="FlexContainer"/> is block-outer + flex-inner;
/// <see cref="InlineFlexContainer"/> is inline-outer + flex-inner. Splitting the
/// product loses no information (every kind names a single dispatch target) and
/// keeps Phase 3 layout's switch statements single-axis.
/// </para>
/// <para>
/// <b>Why explicit inline-* kinds (Task 11 hardening Rec 1).</b> An earlier
/// design used a single <c>AtomicInline</c> kind to mean "any inline-level
/// atomic box (inline-block / inline-flex / inline-grid / inline-table /
/// inline replaced)". That conflation lost the inner formatting context — the
/// flex algorithm and the grid algorithm are completely different, and layout
/// dispatch needed to re-derive "what's inside" from the ComputedStyle. The
/// explicit kinds (<see cref="InlineBlockContainer"/>,
/// <see cref="InlineFlexContainer"/>, <see cref="InlineGridContainer"/>,
/// <see cref="InlineTable"/>, <see cref="InlineReplacedElement"/>) carry the
/// inner FC alongside the outer-display=inline information.
/// </para>
/// <para>
/// <b>Table wrapper vs table grid (Task 11 hardening Rec 5).</b> Per CSS Tables
/// L3 §2.1 a <c>display: table</c> element generates two boxes: the
/// <b>table wrapper box</b> (handles the outer display, margins, captions,
/// floating, positioning) and the <b>table grid box</b> (anonymous, handles
/// the cells/rows/columns and runs the table layout algorithm). We model both
/// — <see cref="Table"/> / <see cref="InlineTable"/> are wrappers,
/// <see cref="TableGrid"/> is the inner grid. <see cref="TableGrid"/> is always
/// anonymous (no source element); the wrapper carries the source.
/// </para>
/// <para>
/// <b>No explicit FlexItem / GridItem.</b> Per CSS Flexbox 1 §4 + Grid 2 §6, a
/// "flex item" or "grid item" is just any in-flow child of a flex/grid container —
/// the same box would have been a regular block-level box in a non-flex context.
/// "Flex-item-ness" is a context-derived property, not an intrinsic kind. Layout
/// dispatch reads the parent's kind to decide which algorithm applies.
/// </para>
/// <para>
/// <b>Out of scope (Phase 3+):</b> ruby boxes (Ruby Layout 1), math boxes
/// (MathML), multicol boxes, SVG boxes, and the various fragmentation-specific
/// boxes (column box, page box, region box). Those land alongside the layout
/// passes that produce them.
/// </para>
/// </remarks>
internal enum BoxKind : byte
{
    /// <summary>The single root of the box tree corresponding to the page /
    /// initial containing block. Generated by <c>BoxBuilder</c> as the parent
    /// of the root element's principal box. Always anonymous (no source element).</summary>
    Root = 0,

    // ============================================================
    // Block-level (outer-display: block — CSS Display L3 §2.4)
    // ============================================================

    /// <summary>A block-level box with inner formatting context = flow — the
    /// default for <c>div</c>, <c>p</c>, <c>section</c>, etc. (<c>display: block</c>).</summary>
    BlockContainer,

    /// <summary>An <c>li</c> element or anything with <c>display: list-item</c>
    /// per Lists L3 §3. Behaves as a <see cref="BlockContainer"/> for layout
    /// but is associated with a separate <see cref="Marker"/> child box.</summary>
    ListItem,

    /// <summary>An anonymous block-level box synthesized to maintain the
    /// invariant that block + inline siblings cannot mix in the same
    /// formatting context per Display L3 §3.1, OR to satisfy table fixup per
    /// Tables L3 §3 (e.g., a stray block inside a table row gets wrapped).
    /// Has no <see cref="Box.SourceElement"/>; inherits style from its parent.</summary>
    AnonymousBlock,

    /// <summary>The block-level <b>table wrapper box</b> for an element with
    /// <c>display: table</c> per Tables L3 §2.1. Owns the outer display +
    /// margins + captions + floating + positioning. Wraps a single anonymous
    /// <see cref="TableGrid"/> child plus zero-or-more <see cref="TableCaption"/>
    /// children.</summary>
    Table,

    /// <summary>A block-level flex container (<c>display: flex</c>) per Flexbox
    /// 1 §3. Lays out its in-flow children per the flex algorithm in §9.</summary>
    FlexContainer,

    /// <summary>A block-level grid container (<c>display: grid</c>) per Grid 2
    /// §3. Lays out its in-flow children per the grid placement + sizing
    /// algorithms in §6 + §11.</summary>
    GridContainer,

    /// <summary>A replaced element (<c>img</c>, <c>video</c>, <c>canvas</c>,
    /// <c>iframe</c>, <c>object</c>, <c>embed</c>) with a block-level outer
    /// display (<c>display: block</c>). The intrinsic content is opaque to
    /// layout — only the intrinsic dimensions matter for sizing per Sizing 3 §5.</summary>
    BlockReplacedElement,

    // ============================================================
    // Inline-level (outer-display: inline — CSS Display L3 §2.4 + Inline L3)
    // ============================================================

    /// <summary>An inline-level non-replaced non-atomic box — <c>span</c>,
    /// <c>em</c>, <c>a</c>. Participates in the parent's inline formatting
    /// context by spawning nested inline runs into line boxes. Inner FC = flow.</summary>
    InlineBox,

    /// <summary>An inline-level atomic box with inner FC = flow-root, i.e.,
    /// <c>display: inline-block</c>. Treated as a single atomic unit by line
    /// layout; the inner BFC lays out independently of the surrounding inline
    /// context per Inline L3 §1.</summary>
    InlineBlockContainer,

    /// <summary>An inline-level atomic box with inner FC = flex
    /// (<c>display: inline-flex</c>). Inner content lays out per the flex
    /// algorithm; the outer box is atomic to line layout.</summary>
    InlineFlexContainer,

    /// <summary>An inline-level atomic box with inner FC = grid
    /// (<c>display: inline-grid</c>). Same atomic-to-line, grid-inside pattern.</summary>
    InlineGridContainer,

    /// <summary>An inline-level atomic <b>table wrapper box</b>
    /// (<c>display: inline-table</c>) per Tables L3 §2.1. Like
    /// <see cref="Table"/> but with inline outer display — wraps a
    /// <see cref="TableGrid"/> + <see cref="TableCaption"/>(s).</summary>
    InlineTable,

    /// <summary>A replaced element with inline-level outer display — the
    /// default for <c>img</c>, <c>video</c>, etc. (no explicit
    /// <c>display: block</c>). Atomic to line layout.</summary>
    InlineReplacedElement,

    /// <summary>An anonymous inline-level box wrapping anonymous text content
    /// per Display L3 §3.2 (e.g., a text node directly inside a flex container
    /// becomes a wrapped flex-item-anon-inline). Distinct from
    /// <see cref="LineBox"/>: this is a box-generation construct,
    /// <see cref="LineBox"/> is a line-layout product.</summary>
    AnonymousInline,

    /// <summary>A contiguous run of text characters within an inline parent.
    /// The smallest text unit Phase 3 segments, shapes, and breaks. Carries
    /// its text in <see cref="Box.Text"/>.</summary>
    TextRun,

    // ============================================================
    // Lists (CSS Lists L3 §3)
    // ============================================================

    /// <summary>The marker box for a <c>list-item</c> per Lists L3 §3.1, or
    /// the <c>::marker</c> pseudo-element box per CSS Pseudo L4 §3.4. Always
    /// has <see cref="BoxPseudo.Marker"/> when generated from a pseudo-element
    /// rule. Outer display depends on <c>list-style-position</c> (inside →
    /// inline-level child of the list-item, outside → outside-the-flow).</summary>
    Marker,

    // ============================================================
    // Table internals (CSS Tables L3 §2 + §3)
    // ============================================================

    /// <summary>The anonymous <b>table grid box</b> per Tables L3 §2.1 — the
    /// inner box that holds the row groups / rows / cells and runs the table
    /// layout algorithm. Always a child of <see cref="Table"/> or
    /// <see cref="InlineTable"/>; never has a source element.</summary>
    TableGrid,

    /// <summary>A row group: <c>tbody</c> or <c>display: table-row-group</c>.</summary>
    TableRowGroup,

    /// <summary><c>thead</c> or <c>display: table-header-group</c>.</summary>
    TableHeaderGroup,

    /// <summary><c>tfoot</c> or <c>display: table-footer-group</c>.</summary>
    TableFooterGroup,

    /// <summary><c>tr</c> or <c>display: table-row</c>.</summary>
    TableRow,

    /// <summary><c>td</c> / <c>th</c> or <c>display: table-cell</c>.</summary>
    TableCell,

    /// <summary><c>colgroup</c> or <c>display: table-column-group</c>.</summary>
    TableColumnGroup,

    /// <summary><c>col</c> or <c>display: table-column</c>.</summary>
    TableColumn,

    /// <summary><c>caption</c> or <c>display: table-caption</c>. A child of
    /// the <see cref="Table"/> / <see cref="InlineTable"/> wrapper, NOT of the
    /// <see cref="TableGrid"/>.</summary>
    TableCaption,

    // ============================================================
    // Layout-time products (not box-generation outputs but live in the tree)
    // ============================================================

    /// <summary>A line box — the per-line container of inline-level boxes
    /// produced by inline-formatting-context layout per Inline L3 §3. One per
    /// rendered line. Always anonymous.</summary>
    LineBox,

    /// <summary>A forced line break — the box generated for <c>&lt;br&gt;</c>
    /// per HTML "Rendering" §15.3.6, which UA stylesheets define as
    /// <c>br { content: "\A"; white-space: pre-line }</c> (i.e., a hard
    /// newline that the inline-formatting-context layout treats as a
    /// mandatory break). Modeling it as its own kind rather than as an
    /// empty <see cref="InlineBox"/> preserves the line-break semantics
    /// for Phase 3 line layout — an empty inline would silently disappear
    /// during line construction. Always inline-level + atomic from line
    /// layout's view.</summary>
    LineBreak,
}

/// <summary>Pure facts about a <see cref="BoxKind"/>, factored out so that callers OUTSIDE the box tree
/// (e.g. <see cref="MarginContentCollector"/> classifying running-content block boundaries) share the SAME
/// block-level-outer classification as <see cref="Box.IsBlockLevel"/> — one source of truth (post-PR-#154
/// review P3).</summary>
internal static class BoxKindFacts
{
    /// <summary><see langword="true"/> when <paramref name="kind"/> generates a BLOCK-LEVEL outer display
    /// per CSS Display L3 §2 — the set <see cref="Box.IsBlockLevel"/> reports.</summary>
    public static bool IsBlockLevelOuter(BoxKind kind) => kind switch
    {
        BoxKind.Root or BoxKind.BlockContainer or BoxKind.ListItem
            or BoxKind.AnonymousBlock or BoxKind.Table or BoxKind.FlexContainer
            or BoxKind.GridContainer or BoxKind.BlockReplacedElement => true,
        _ => false,
    };
}
