// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

namespace NetPdf.Layout.Boxes;

/// <summary>
/// Pseudo-element designation for a <see cref="Box"/>. When a box represents content
/// generated by a <c>::before</c> / <c>::after</c> / <c>::marker</c> / <c>::first-line</c>
/// / <c>::first-letter</c> rule per CSS Pseudo L4, this enum disambiguates which one —
/// the box's <see cref="Box.SourceElement"/> still points at the originating element,
/// but the box itself represents the synthesized pseudo-content.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a separate enum vs encoding into <see cref="BoxKind"/>.</b> The pseudo
/// designation is orthogonal to the box's layout role: a <c>::before</c> box can be a
/// <see cref="BoxKind.BlockContainer"/> (if <c>display: block</c>), an
/// <see cref="BoxKind.InlineBox"/> (the default), or a <see cref="BoxKind.AtomicInline"/>
/// (if <c>display: inline-block</c>). Stuffing the pseudo into BoxKind would multiply the
/// kind matrix unnecessarily.
/// </para>
/// <para>
/// <b>Coverage.</b> Cycle-1 (Task 14 Pseudo materialization) wires the five spec-defined
/// generated-content pseudos. Highlight pseudos (<c>::selection</c>, <c>::target-text</c>,
/// <c>::spelling-error</c>, <c>::grammar-error</c>) are post-v1 — they're paint-time
/// overlays, not box-generation pseudos.
/// </para>
/// </remarks>
internal enum BoxPseudo : byte
{
    /// <summary>Not a pseudo-element — the box represents the
    /// <see cref="Box.SourceElement"/> directly.</summary>
    None = 0,

    /// <summary><c>::before</c> per Pseudo L4 §3.1 — content generated before the
    /// element's children.</summary>
    Before,

    /// <summary><c>::after</c> per Pseudo L4 §3.2 — content generated after the
    /// element's children.</summary>
    After,

    /// <summary><c>::marker</c> per Pseudo L4 §3.4 — the list-item marker.
    /// Always paired with a <see cref="BoxKind.Marker"/> kind.</summary>
    Marker,

    /// <summary><c>::first-line</c> per Pseudo L4 §3.5 — the first formatted line
    /// of a block container.</summary>
    FirstLine,

    /// <summary><c>::first-letter</c> per Pseudo L4 §3.6 — the first letter of the
    /// first formatted line.</summary>
    FirstLetter,
}
