// Copyright 2026 Roland Aroche and NetPdf contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

namespace NetPdf.Layout.Boxes;

/// <summary>
/// Pseudo-element designation for a <see cref="Box"/>. When a box represents content
/// generated by a <c>::before</c> / <c>::after</c> / <c>::marker</c> rule per
/// CSS Pseudo L4, this enum disambiguates which one — the box's
/// <see cref="Box.SourceElement"/> still points at the originating element, but the
/// box itself represents the synthesized pseudo-content.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a separate enum vs encoding into <see cref="BoxKind"/>.</b> The pseudo
/// designation is orthogonal to the box's layout role: a <c>::before</c> box can be
/// a <see cref="BoxKind.BlockContainer"/> (if <c>display: block</c>), an
/// <see cref="BoxKind.InlineBox"/> (the default), or an
/// <see cref="BoxKind.InlineBlockContainer"/> (if <c>display: inline-block</c>).
/// Stuffing the pseudo into BoxKind would multiply the kind matrix unnecessarily.
/// </para>
/// <para>
/// <b>What's NOT here, and why.</b> <c>::first-line</c> and <c>::first-letter</c>
/// are deliberately excluded: per CSS Pseudo L4 §3.5–§3.6 + Inline L3, the text
/// they affect depends on line-breaking decisions made during layout (which
/// characters fit on the first line, which letter is the "first" after stripping
/// punctuation, where soft-wrap opportunities lie). They cannot be materialized
/// as boxes during the box-generation DOM walk — the box tree exists before line
/// layout has run. The cascade tracks them in a separate fragment-style table
/// applied during line layout (cycle-2 work). Highlight pseudos
/// (<c>::selection</c>, <c>::target-text</c>, <c>::spelling-error</c>,
/// <c>::grammar-error</c>) are likewise paint-time overlays, not box-generation
/// pseudos, and are post-v1.
/// </para>
/// </remarks>
internal enum BoxPseudo : byte
{
    /// <summary>Not a pseudo-element — the box represents the
    /// <see cref="Box.SourceElement"/> directly.</summary>
    None = 0,

    /// <summary><c>::before</c> per Pseudo L4 §3.1 — content generated before the
    /// element's children.</summary>
    Before,

    /// <summary><c>::after</c> per Pseudo L4 §3.2 — content generated after the
    /// element's children.</summary>
    After,

    /// <summary><c>::marker</c> per Pseudo L4 §3.4 — the list-item marker.
    /// Always paired with a <see cref="BoxKind.Marker"/> kind (enforced by the
    /// <see cref="Box"/> constructor).</summary>
    Marker,
}
